### ISSUE TITLE
Find building by building address

### ISSUE THREAD

**Issue by goiaba** [sauloaguiar/grab-your-pack-server#9]
During the process of registering user's building/apartment we must be able to check if the building and apartment being registered already exists in the database. Expose an endpoint that verifies if a building already exists and return it if so.

method: GET
URI: /buildings/?address_1={address_1}&address_2={address_2}&city={city}&state={state}&country={country}&zip_code={zip_code}
return: Building JSON object

**Comment by sauloaguiar** [comment]
Make sure that Buildings addresses are unique in the database.

**Comment by sauloaguiar** [comment]
It's forcing a building parameter in the request.
